spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tywxk123
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&characterEncoding=UTF-8
    hikari:
      charset: UTF-8
